import DS from 'ember-data';

export default DS.Model.extend({
  authKeyID: DS.attr('number'),
  authorityEffectiveDate: DS.attr('date'),
  authorityExpiryDate: DS.attr('date'),
  marketManager: DS.attr('string'),
  accountManager: DS.attr('string'),
  customerPayer: DS.attr('string'),
  //commodityCode: DS.attr('number'),
  //commodityDescription: DS.attr('string'),
  majorLocations: DS.attr('string'),
  authoritySCAC: DS.attr('string'),
  authorityNumber: DS.attr('string'),
  authorityId: DS.attr('string'),
  annualCarLoadsforthisAgreement: DS.attr('number'),
  annualNetRevenueBeforeRenewal: DS.attr('number'),
  avgRCRBeforerenewal: DS.attr('number'),
  avgCCDForCNSuppliedEqptBeforeRenewal: DS.attr('number'),
  generalComments: DS.attr('string'),
  fuelSurchargeTariffapplied: DS.attr('string'),
  priceIncreaseatLastRenewalActual: DS.attr('number'),
  priceIncreaseforThisRenewalCN: DS.attr('number'),
  priceIncreaseforThisRenewalCustomer: DS.attr('number'),
  allowedtoExpire: DS.attr('string'),
  authorityType: DS.attr('string'),
  version: DS.attr('string'),
  firstSeniorApprover: DS.attr('string'),
  firstSeniorApproverApprovalStatus: DS.attr('string'),
  firstSrApprSubmittedDate: DS.attr('date'),
  firstSrApprApprovedRejectedDate: DS.attr('date'),
  secondSrApprApprovalStatus: DS.attr('string'),
  secondSrApprSubmittedDate: DS.attr('date'),
  secondApprApprovedRejectedDate: DS.attr('date'),
  businessTeamDescription: DS.attr('string'),
  preparedbyDate: DS.attr('date'),
  updatedbyDate: DS.attr('date'),
  rev: DS.attr('string'),
  coms: DS.hasMany('commodity', { inverse: "publications" , async: true } )
});
